### PR TITLE
draw_line_string mode tests

### PR DESCRIPTION
**Pull request by davidtheclark**
Continuation of #384

### CODE REVIEW

**Comment by davidtheclark** [comment]
@mcwhittemore ready for review

**Comment by mcwhittemore** [comment]
Can you add a test where you start drawing and than exit before a click. This should get this mode to 100%.

image

**Comment by mcwhittemore** [comment]
This works well. Once you add that last test, lets merge.

**Comment by davidtheclark** [comment]
@mcwhittemore I think I was able to just delete that line, because the deletion of incomplete elements is already done in https://github.com/mapbox/mapbox-gl-draw/pull/388/files#diff-7a0124268c46d39459f7595fd9d4d1caR75 as far as I can tell.

**Pull request merged**
