### PR TITLE
Common Interface for sub controls and one store

### PR DESCRIPTION
**Pull request by mcwhittemore**
@edenh & @kelvinabrokwa 

Here is where I am in my pursuit of moving gl-draw to enforce a standard interface for its sub controls and then move it to one store. There are few rendering bugs that I'm working on currently. Once I've got those fixed, the common interfaces need to be touched up a bit and documented and than I'll move onto the single store.

There are a few things I'm not too happy about (draw_events for one) so I might try to clean those up a bit more too.

I'd love some feedback and questions to what I'm doing here to make sure I'm not missing something major.

### CODE REVIEW

**Comment by mcwhittemore** [comment]
Currently this is at 48-52 FPS for a few features.

## Bugs fixed by this

- [ ] #148

**Comment by mcwhittemore** [comment]
The last thing that needs to go on here is to go through the api docs and make sure nothing was broken. I think we should just dump these use cases into debug for now and then write them as tests after this lands.

@kelvinabrokwa thoughts?

@tmcw wanna take sometime to review this?

**Comment by kelvinabrokwa** [comment]
@mcwhittemore 
TO DO

- [ ] trash button doesn't show on shift-drag selection

**Comment by mcwhittemore** [comment]
@kelvinabrokwa wanna take a shot at those two things?

**Comment by kelvinabrokwa** [comment]
@mcwhittemore yup

**Comment by mourner** [comment]
@mcwhittemore this is really cool! What was the main performance hog for #94?

**Comment by mcwhittemore** [comment]
@mourner - there were a few things I did in general. One was to remove the geometry request in the featureAt calls. The second was to reduce the featureAt calls and the setData calls. Now we are only setting data once or twice per frame where before we were setting in on every mouse event.

**Comment by mcwhittemore** [comment]
To be honest, I'm still not sure how much of a perf gain this branch has. Sometimes I see a 10fps gain, other times I see a 1 to 2 fps drop.

**Pull request merged**
