### PR TITLE
Format map.fire call to match breaking change

### PR DESCRIPTION
**Pull request by tristen**
Taking the easy way out. A complete solution would re-write the draw tools API with its own `draw.on('create')` using something like EventEmitter. 

ref #766

### CODE REVIEW

**Comment by mcwhittemore** [comment]
@tristen - I'd like to have this to not be a breaking change. Is it possible for us to know which version of `fire` is in mapbox-gl?

**Comment by tristen** [comment]
> @tristen - I'd like to have this to not be a breaking change. Is it possible for us to know which version of `fire` is in mapbox-gl? 

This change still uses `fire`. It's just that its a private method now and argument signature has changed. The API should remain the same. I think this is close as we can get without dire breaking changes (although it does result in `peerDependencies` being pinned to `mapbox-gl-js@0.45.0`)

**Comment by mcwhittemore** [comment]
This PR currently requires all users of Draw to update to `mapbox-gl@0.45.0-beta.1` which is the breaking change I'm noting.

**Comment by tristen** [comment]
OK. I guess what we could do look at `mapboxgl.version` and format the argument differently.

**Comment by mcwhittemore** [comment]
> we could do look at mapboxgl.version and format the argument differently.

Cool! This will probably set us up to do the EventEmitter option as well.

**Comment by mollymerp** [comment]
thanks for taking this on @tristen – let me know if you need anything!

**Comment by tristen** [comment]
I think this _still_ results in a breaking change. version would need to be passed as an option

```js
new MapboxDraw({
  version: mapboxgl.version
});
```

Which we can helpfully throw as an error if the user hasn't passed one?

**Comment by tristen** [comment]
🚶 https://github.com/mapbox/mapbox-gl-draw/pull/772

**Pull request closed without merging**
