### PR TITLE
Draw should not interfere with dragPan.disable() 

### PR DESCRIPTION
**Pull request by itoxiq**
Continuation of #1191

The issue is that Draw assumes that dragPan is enabled and simply enables it without question after certain operations (when dragpan is temporarily disabled). This change would set a variable called initialDragPanState and only re-enables when it was originally enabled.

### CODE REVIEW

**Comment by iToXiQ** [comment]
@stepankuzmin

**Review by stepankuzmin — APPROVED** [review]
Looks good to me, thanks for the contribution @itoxiq 👍

**Comment by fede-qubika** [comment]
@itoxiq @stepankuzmin hey guys, after clicking the same feature multiple times without moving the mouse, doesn't it happen to you that dragPan remains disabled, regardless of whether it was initially enabled? I just updated to version 1.5.0, and this issue started happening

**Comment by underoot** [comment]
@fede-qubika The issue was addressed. Thank you for the report!

**Pull request merged**
