### PR TITLE
Add back layers and force redraw after map style change

### LINKED ISSUE #512: Draw plugin breaks when map style changes
When I draw something on map and I change the map style, draw plugin breaks and I can't draw anything more. Draw plugin throws me this error:

`"The layer 'gl-draw-polygon-fill-inactive.cold' does not exist in the map's style and cannot be queried for features."`

Example:
http://codepen.io/Naimikan/pen/JRJOVN?editors=1111

I want to draw a polygon on style, save it, change style and continue drawing other polygons on other styles. I think I have to create style's layer on style change because style change won't do it by itself.

### PR DESCRIPTION
**Pull request by jisaacks**
Fixes #512 

This seems to fix it. Not sure it is the best solution, I had to attach `setup` to the `context` so I could re-invoke `setup.addLayers`.

I also has to first change mode to "static" before changing it back to what it previously was (forcing a re-render) otherwise the change mode is ignored.

If you want me to change anything let me know.

### CODE REVIEW

**Comment by mcwhittemore** [comment]
merged via 7511c0142e8cae58c5f57803b62440ffea6b7ee1

**Comment by mcwhittemore** [comment]
@jisaacks - thanks for this.

I changed two things before merging this. First I had `setup` add itself to `ctx` and second I used `store.setDirty()` and `store.render()` to force the render so we could avoid changing modes.

**Comment by jisaacks** [comment]
Sounds good, thanks!

FYI, browsing the updated code, it looks like there is a mistake, [adding the event, when it should be removing it](https://github.com/mapbox/mapbox-gl-draw/blob/master/src/events.js#L179). Sorry about that! I can add a PR if you want but it's trivial and probably not worth one if you want to just change the word from `on` to `off`. Let me know.

Thanks!

**Comment by mcwhittemore** [comment]
Nice catch. Thanks! 

c230ca1e1f37647f50a032ec0c50f88af2dc9844

**Pull request closed without merging**
