### PR TITLE
[WIP] Feature/605 line continuation

### PR DESCRIPTION
**Pull request by drewbo**
Implements line continuation, towards #605:

- [x] Needs a test or two
- [x] Implements "continue from beginning" by mutating the original feature to reverse the coordinates array. I didn't feel great doing it but if you don't, and just set `currentVertexPosition` to 0, subsequent edits get really wacky (it tries to edit the existing vertices in turn). Thoughts on how terrible this is?
- [x] I could go either way with `from` requiring `start`/`end` vs. requiring an actual coordinate but [leaning toward the latter](https://github.com/mapbox/mapbox-gl-draw/issues/605#issuecomment-284810522)

### CODE REVIEW

**Comment by mcwhittemore** [comment]
> Implements "continue from beginning" by mutating the original feature to reverse the coordinates array. ... Thoughts on how terrible this is?

I'd say this is pretty bad. The problem is that a user will not notice that this happens, so while 90% of the time the order doesn't matter, there is going to be times when it does and those users are not going to know why the order has been broken.

To do this I think we need to use [line.addCoordinate](https://github.com/mapbox/mapbox-gl-draw/blob/master/src/feature_types/line_string.js#L13) to get the new position into the line rather than just setting the position via `line.updateCoordinate`.

> I could go either way with from requiring start/end vs. requiring an actual coordinate but leaning toward the latter

I imagine that we'll want to go from `direct_select` mode to `draw_line_string` mode once we have this functionality. I guess we could do this by adding `start` and `end` to the corresponding positions in the line string. This doesn't really work well for polygons though.

One problem with the `coord_path` option is that then you'd need to figure out which direction you are adding in. This might be trivial I guess.

**Comment by drewbo** [comment]
@mcwhittemore updated the logic to not mutate the array. It requires tracking an internal variable "direction" within the mode which is a little inelegant but works out nicely. Let me know if this approach looks correct and I can write some tests and make any requested changes to the `from`:`start`/`end` API

**Comment by drewbo** [comment]
@mcwhittemore also updated the `from` property to take coordinate. So for an existing line with id as `'a'` and coordinates `[0,0]` and `[0,1]` you can call `Draw.changeMode('draw_line_string', { featureId: 'a', from: [0,0] })` or `Draw.changeMode('draw_line_string', { featureId: 'a', from: [0,1] })`. I like this pattern better because it is very transparent from the users' perspective. Three different errors are thrown (no matching feature, invalid or missing `from` parameter, or `from` coordinate not at the start/end of the coordinate array)

**Comment by mcwhittemore** [comment]
@drewbo - I'm getting an error trying to use this. Here is the error and the JSON of the feature I'm trying to edit.

image

```
{
  "id": "15957cf9ad4c342a818b4d69323edfc4",
  "type": "Feature",
  "properties": {},
  "geometry": {
    "coordinates": [
      [
        -67.675781249997,
        4.214943141401079
      ],
      [
        -60.29296874999898,
        -31.952162238018474
      ],
      [
        -25.136718749999744,
        -27.371767300513696
      ],
      [
        -17.050781249993236,
        6.315298538345601
      ]
    ],
    "type": "LineString"
  }
}
```

**Comment by drewbo** [comment]
@mcwhittemore that looks like the "right" error (although it could definitely use some copy editing). For that string you should either send `[-67.675781249997,4.214943141401079]` or `[-17.050781249993236,6.315298538345601]` (the endpoint coordinates) as the `from` property

**Comment by mcwhittemore** [comment]
Ah. Thanks. This is looking good. Let's get the tests and docs updated and merge!

**Comment by drewbo** [comment]
@mcwhittemore added tests and updated docs. One tiny lingering oddity: the current line drawing mechanism uses `line.updateCoordinate` with an index just beyond the current array to add new coordinates (this likely occurs in the `mousemove` listener on desktop and on the next click on mobile). The `'backwards'` continuation that this new feature requires (traversing the coordinates array in reverse) means that we have to explicitly call `line.addCoordinate` on click to add another dummy coordinate which can then be updated on move. So the tests have to [check for one extra coordinate](https://github.com/mapbox/mapbox-gl-draw/pull/606/commits/97b6805bcb6a723f2935f08e325597f160e12195#diff-d2ca2412af668e11090c45aae155d421R656) when counting in that direction (although it isn't saved and doesn't cause issues? maybe on mobile?). Concerns?

**Comment by mcwhittemore** [comment]
@drewbo - I think this is good. I double checked that the coordinates look right and I think we're good. I'm not 100% sure if this will work right on touch, but I don't have a good way to test this right now so I'm going to merge and we can bug fix if needed.

**Comment by mcwhittemore** [comment]
Github isn't getting that this has been merged via the command line.

001a23e7544e60a3e06406c7488b1e384aed0801

**Pull request closed without merging**
