### PR TITLE
Updated controls ordering and UI tooltips to be consistent with keybindings

### PR DESCRIPTION
**Pull request by georgemoon**
At some point the Mapbox Draw keybindings were changed, and are now:

(1) Point
(2) Line
(3) Polygon

whereas the tooltips still have the letters l/p/m.

This pull request changes the tooltips, and also the ordering of the controls to be consistent with the numbering used.

Addresses #1103

### CODE REVIEW

**Review by stepankuzmin — APPROVED** [review]
Good catch! Thanks @georgemoon 👍

**Comment by georgemoon** [comment]
Hey @underoot @stepankuzmin, I think this change is still relevant but doesn't appear to have been included in the latest refactor. Could you maybe take another look? It's a relatively simple fix! Thanks

**Comment by underoot** [comment]
Hey, @georgemoon! You are right, by mistake your changes haven't been included into v1.5.0. I've refreshed PR branch and changes for some reasons weren't reflected in GitHub and I thought that changes already propogated to `main`. I've created  #1320 to follow-up and indeed merge changes. Thank you!

**Comment by georgemoon** [comment]
Great, thanks!

**Pull request closed without merging**
