### PR TITLE
Ensure tap-dragging fires an update event

### PR DESCRIPTION
**Pull request by Zirak**
Tap dragging did not fire a `draw.update` event, leading to much confusion.

In the interim, a fairly simple fix is to add the following *before* creating the relevant `MapboxDraw` instance:

```js
MapboxDraw.modes.simple_select.onTouchEnd = MapboxDraw.modes.simple_select.onMouseUp;
```

### CODE REVIEW

**Comment by trygveaa** [comment]
I also ran into this issue. Can confirm that the fix is working properly. Can it be merged?

**Comment by Zirak** [comment]
>
> I also ran into this issue. Can confirm that the fix is working properly. Can it be merged?

Until such a fateful day, you can workaround this bug as outlined in the PR message:

> ```js
> MapboxDraw.modes.simple_select.onTouchEnd = MapboxDraw.modes.simple_select.onMouseUp;
> ```

**Comment by trygveaa** [comment]
Thanks, yeah I know, but it's always better to have the fix upstream. And it would save time for the next person running into this.

**Comment by trygveaa** [comment]
@karimnaaji: Why was this closed? The issue still remains as far as I can see.

**Comment by karimnaaji** [comment]
Oups sorry about that @trygveaa ! We did a change of repository default branch yesterday and github closed all the PRs that were targetting the old branch as default target, this is the only PR we did not reopen.

**Comment by trygveaa** [comment]
Oh, so that's what happened. I did wonder why all my PRs were closed and reopened.

You have to change the destination too though. I see you have done it for most, but not all PRs.

**Comment by karimnaaji** [comment]
Yep working on it now :)

**Review by stepankuzmin — APPROVED** [review]
This was fixed before, but I will merge it to keep the unit test. Thanks for the contribution @Zirak!

**Pull request merged**
