### PR TITLE
fixing context issue and adding rectangle draw ability

### PR DESCRIPTION
**Pull request by miller-austin**

### CODE REVIEW

**Comment by jo-chemla** [comment]
Would love to see this rectangle drawing added in core mapbox-gl-draw! Tried importing [mapbox-gl-draw-rectangle-mode](https://github.com/thegisdev/mapbox-gl-draw-rectangle-mode) as a mode in a react MapboxDraw component with no luck

**Comment by miller-austin** [comment]
> Would love to see this rectangle drawing added in core mapbox-gl-draw! Tried importing [mapbox-gl-draw-rectangle-mode](https://github.com/thegisdev/mapbox-gl-draw-rectangle-mode) as a mode in a react MapboxDraw component with no luck

Make sure to add it to your modes similar to this
`const modes = MapboxDraw.modes;
modes.draw_rectangle = DrawRectangle;

const draw = new MapboxDraw({
  modes: modes
});

draw.changeMode('draw_rectangle');`

**Comment by jo-chemla** [comment]
Hi Miller! Just saw your message, thanks for replying (message disappeared, shown in PS for ref)
I tried the following with no luck, since typescript type checking won't let me pass the draw_rectangle string in the MapboxDraw changeMode method. 
```
      const draw = new MapboxDraw(props);
      draw.changeMode('draw_rectangle');
```
Do you think this rectangle drawing ability will be added to mapbox-gl-draw as w core feature at some point? Thanks!


PS: original answer: 
Make sure to add it to your modes similar to this
```
const modes = MapboxDraw.modes;
modes.draw_rectangle = DrawRectangle;
const draw = new MapboxDraw({
modes: modes
});
draw.changeMode('draw_rectangle');
```

**Comment by miller-austin** [comment]
At this point, I would doubt that they add it to the original repo, but I'm not a maintainer so I'm not sure. (I ended up forking the repo and making changes to match our needs) You could try `@ts-ignore` for that line and make sure to have @types/mapbox__mapbox-gl-draw installed.

**Comment by jo-chemla** [comment]
Thanks for the reply, I thought you were part of the core maintainers! :)


ts-ignore indeed does the trick, so I can build a custom button and edit the draw mode when this button is clicked - passing the correct setDrawMode.

One last thing: is there an easy way to add a button for CustomControls, right below the existing controls buttons (draw polygon, trash etc)?


Thanks again for your help!

________________________________

**Pull request closed without merging**
