### PR TITLE
Throttle instead of debounce

### LINKED ISSUE #89: Bad drawing/editing performance
While you draw a polygon, the shapes are updated super-fast. But when you finish the shape and then edit it, dragging points is super-slow and laggy for some reason. I'm sure this can be fixed. cc @kelvinabrokwa

### PR DESCRIPTION
**Pull request by mourner**
Closes #89, makes drawing and editing much snappier (together with mapbox-gl-js master version).

### CODE REVIEW

**Comment by mourner** [comment]
cc @mcwhittemore @kelvinabrokwa

**Comment by averas** [comment]
:+1: Awesome! I'd say this takes this library a lot closer to 1.0..

**Comment by kelvinabrokwa** [comment]
@mourner Good work! It seems like beginning of drags is very choppy. Are you seeing this on your machine in chrome?

**Comment by mourner** [comment]
@kelvinabrokwa nope, looks fine on my Chrome/OSX.

**Comment by averas** [comment]
Works fine here too. @kelvinabrokwa Did you make sure you pulled the latest commits on mapbox-gl-js? The Chrome-related dragging issues were apparently solved as a side effect of https://github.com/mapbox/mapbox-gl-js/pull/2142 which was merged as late as yesterday.

**Comment by mcwhittemore** [comment]
Thanks for this @mourner. I'll note that throttle is better for this kind of thing for the future. :smile:

**Pull request merged**
