### PR TITLE
Shift clicking

### PR DESCRIPTION
**Pull request by davidtheclark**
Ref #440.

This was one of those cases where to debug the problem I just had to clarify all the logic, so I understood it better and knew there weren't false moves.

So I refactored simple_select and I think it's more clear and more precise now. I believe clarifying process fixed our shift-click problems. 

The UI works as before, from what I can tell, and tests are passing (I removed two that seemed unnecessary, because UI confirmed that double-click zoom was behaving normally).

### CODE REVIEW

**Comment by davidtheclark** [comment]
@mcwhittemore for review.

**Comment by mcwhittemore** [comment]
bad-select

**Comment by mcwhittemore** [comment]
@davidtheclark this looks pretty good. I found one bug.

**Comment by davidtheclark** [comment]
@mcwhittemore I think I reproduced that and fixed it. The problem was that you could select multiple features then shift-click to drag move and box select at the same time. Now it will just drag move (not box select).

**Pull request merged**
