### PR TITLE
Check `lineBasePath` parameter

### PR DESCRIPTION
**Pull request by ilyamilosevic**
PR for issue #484.

### CODE REVIEW

**Comment by ilyamilosevic** [comment]
O-o-ops... It's a bummer. Didn't run the tests.

**Comment by mcwhittemore** [comment]
@ilyamilosevic thanks for this fix. We use it looks like this value can be null at times which is causing your problem.

- Expected: `coord_path: '0'`
- Found: `coord_path: 'null.0'`

**Comment by ilyamilosevic** [comment]
@mcwhittemore, thanks you guys, too, for sharing this another good Mapbox project! Unfortunately, if I change comparison to `lineBasePath != undefined` (which, if I not mistaken, includes `null`) tests fail again with message: `# createSupplementaryPoints with MultiLineString, midpoints, selected coordinate not ok 159 should be equivalent`.

**Comment by mcwhittemore** [comment]
@ilyamilosevic hmmmm... this could be a failure in our test suite... what is the `typeof lineBasePath`? Any chance that could work as a check for you?

**Comment by ilyamilosevic** [comment]
@mcwhittemore, nope, not working. By the way, why for first LineString in MultiLineString geometry `coord_path` property of corresponding supplementary points is not two-dimensional? For example, on this line: https://github.com/mapbox/mapbox-gl-draw/blob/master/test/create_supplementary_points.test.js#L397

**Comment by mcwhittemore** [comment]
Vertexes related to LineStrings should have a one-dimensional coord_path as this tells which Position the vertex relates to. For MultiLineStrings it should be two-dimensional (telling us which line and than which Position)

**Comment by mcwhittemore** [comment]
@ilyamilosevic I've rebased and merged your via #485. Thanks!

**Comment by ilyamilosevic** [comment]
@mcwhittemore Great! I've closed issue #484.

**Pull request closed without merging**
