### PR TITLE
Skip rerenders for mousemove handlers when in selection modes

### PR DESCRIPTION
**Pull request by kkaefer**
Reduces CPU usage and fixes https://github.com/mapbox/mapbox-gl-draw/issues/760

CPU usage is still high when moving the mouse, but the remaining CPU usage is in queryRendereredFeatures which is used to determine the shape of the mouse pointer.

### CODE REVIEW

**Comment by robhawkes** [comment]
This is great, would love to see it get merged so I don't need to run a custom build of draw. 👍

**Comment by JamesLMilner** [comment]
Would also love to see this merged if possible :) I think it'd be a great improvement.

**Comment by jayarjo** [comment]
Any idea when there will be a release with this?

**Comment by usb248** [comment]
I tested this PR and it causes a bug.
These lignes of code : https://github.com/mapbox/mapbox-gl-draw/pull/944/files#diff-2650e3200d76013773ddf2af657f5a3dR40-R43.
On the first click (quick mousedown+mouseup) on a feature, the feature doesn't enter in selection owing to a "glitch" (re-render ?).

Please **fix this bug** or **not merge** this PR.
thanks

**Pull request merged**
