### PR TITLE
Enable automatic s3 deployment

### PR DESCRIPTION
**Pull request by lucaswoj**
This PR enables automatic s3 deployment which publishes to s3 via CircleCI whenever a release tag is pushed to GitHub. This frees us from having to do deployment manually within the GL JS repository.

Related to https://github.com/mapbox/mapbox-gl-js/pull/4305

### CODE REVIEW

**Comment by mcwhittemore** [comment]
@lucaswoj this looks good to me. How do I test it?

**Comment by lucaswoj** [comment]
@mcwhittemore You can test by pushing any new tag to the repo. (We can restrict this criteria later if we want to only target tags that look like release tags). I've tested it with a `v0.16.0-dev` tag which has been published here: https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-draw/v0.16.0-dev/mapbox-gl-draw.js

**Comment by mcwhittemore** [comment]
OK. So when this tag is pushed, travis pulls down the tag, does a build and pushes `/dist` to s3? Do we need to do anything to make sure `/dist` is up to date?

**Comment by lucaswoj** [comment]
`dist` is made up to date by the [npm `build` script, which is run automatically during package installation](https://docs.npmjs.com/cli/build)

**Comment by mcwhittemore** [comment]
@lucaswoj - this looks good to me

**Pull request merged**
