### PR TITLE
Add mouseout and use it to cancel box select; fixes #419

### LINKED ISSUE #419: Box selecting outside browser viewport breaks
If I shift click to box select and then move the cursor outside the browser viewport, the box is still rendered but deactivated. I return the cursor to the viewport and try to continue the box selection, but it is essentially broken.

jun-27-2016 13-14-22

### PR DESCRIPTION
**Pull request by davidtheclark**
Re-take on PR #444 to close bug #419.

This time I used `events.js` to add the DOM listener, and added some appropriate tests.

@mcwhittemore, ready for review.

### CODE REVIEW

**Comment by mcwhittemore** [comment]
Rebasing

**Comment by mcwhittemore** [comment]
@davidtheclark this is looking good. There is a bug with mouseout when dragging a vertex as well.

mouse out drag

**Comment by davidtheclark** [comment]
Additionally, weird stuff happens if you try to drag-move a feature east or west beyond the canvas.

**Comment by davidtheclark** [comment]
This might be an issue with mapbox-gl-js. It seems like if I mousedown then drag off the canvas I can dragPan even if I've disabled drag pan and it doesn't work *on* the canvas.

**Comment by davidtheclark** [comment]
@mcwhittemore With the latest commit, feature drag-moving should stop when you leave the canvas, without any weird dragPanning taking its place.

If you get a minute and can review this from a UX perspective, that'd be great. If we like the interaction, I'll modify the tests for them.

Another related bug that may need to be addressed as part of this: I shouldn't be able to warp features by  drag-moving such that part of them moves past a pole, north or south. Probably we need to say that whenever the northern-most vertex of any selected feature hits the north pole (or reverse for south), the movement stops?

**Comment by davidtheclark** [comment]
@mcwhittemore Per the scrum conversation, I'll save the dragging-past-poles bug for another PR. And I guess I didn't break any tests with this one, so it's ready for review & maybe merge.

**Comment by mcwhittemore** [comment]
@davidtheclark I'm seeing a bug with dragging a point off the screen.

drag_out

Also, should it stop drag in simple_select or just hold off on it until the mouse comes back in...

**Comment by davidtheclark** [comment]
@mcwhittemore That direct_select problem was a silly last minute mistake I made before pushing. Should be fixed now.

jul-05-2016 11-53-04

And yes, I guess it would be nice if the moving just held off until you returned to the canvas. I'll work on that.

**Comment by davidtheclark** [comment]
So, turns out we may not need the `mouseout` functionality after all. With the latest commit. You can drag off the canvas and the movement will stop, then it will resume when you bring the mouse back on the canvas. Same goes for box select. 

Seems to work pretty well. The only thing about this that I think is a little funny is that you can release the mouse while off-canvas and when you go back on-canvas you're continuing the interaction as though you we were still dragging. I'm worried we may have to choose between this weirdness, or the weirdness (from before the latest commit) of fully cancelling your drag event when you leave the canvas even if you keep holding the mouse key down.

**Comment by davidtheclark** [comment]
Ah, good thinking. I guess if the buttons aren't down on a mousemove we could cancel the action.

**Comment by davidtheclark** [comment]
Ok, @mcwhittemore, I think it's on track now. I learned that the internal `drag` and `mousemove` events are mutually exclusive based on the mouse's buttons, so I added a couple of lines to cancel these extended interactions if there's a mousemove event that is not a drag.

**Comment by mcwhittemore** [comment]
@davidtheclark sadly the difference between mousemove and drag in Draw is if the mouseup event happened and since mouseup events don't happen when the mouse is off this doesn't work.

That said, I like the idea here. Lets have the event.js set `mouseDownInfo.isDown = false` on a mouseout event.

**Comment by mcwhittemore** [comment]
Also, it looks like there is a `which` attribute on MouseEvents. But MDN tells you to not use it so I'd say we shouldn't use it.

**Comment by davidtheclark** [comment]
> sadly the difference between mousemove and drag in Draw is if the mouseup event happened

Could we not at this line https://github.com/mapbox/mapbox-gl-draw/blob/master/src/events.js#L39 use `event.originalEvent.buttons !== 1` instead of the `mouseDownInfo`?

**Comment by mcwhittemore** [comment]
Looks like it doesn't work on Safari...

image

**Comment by davidtheclark** [comment]
Damn this is has proven to be quite a pain. One more commit to fix it all ...

**Comment by davidtheclark** [comment]
Agh, that puts us back in our original situation where it doesn't matter whether you hold the mouse down or not when you go off canvas ...

**Comment by mcwhittemore** [comment]
@davidtheclark I'm good with this commit https://github.com/mapbox/mapbox-gl-draw/pull/449/commits/aefb1fa366ac0521c67368df9893f08c2f6a75bd

**Comment by davidtheclark** [comment]
Ok, @mcwhittemore, here it is. Summary of the changes:

- Mouse events now determine whether we have `drag` or `mousemove` based on whether `event.which === 1` (that's drag). This is so that if a user drags off the canvas, mouseups off canvas, then moves the mouse back on canvas, the drag does not resume.
- `moveFeatures()` is its own external function. This happened during an experiment but makes sense, I think, so I kept it; and it will make even more sense once the next adjustment comes in (which will prevent you from moving parts of features past poles).
- Fixed the bug in both `simple_select` and `direct_select` mode where if you dragged off-canvas the map's dragPan kicked in right away, causing weird jumps.
- Updated and added tests.

**Comment by mcwhittemore** [comment]
This looks good. Rebasing. Once the tests pass, I'll merge.

**Pull request merged**
