### PR TITLE
Issue #654 retaining dragPan state for simple_select, direct_select, and setup 

### PR DESCRIPTION
**Pull request by holyblader2010**

### CODE REVIEW

**Comment by holyblader2010** [comment]
Looks like mapbox-gl-js-mock is missing the dragPan.isEnabled function.
I suppose this will require some unrelated updates to pass the automated tests.

**Comment by mcwhittemore** [comment]
Yea... I wish we did mocking better here.

**Comment by alexgleith** [comment]
I think this may be resolved in my past PR. #696

**Comment by mcwhittemore** [comment]
Unless im mistaken, this has been covered by #696. Please reopen if I'm wrong.

**Comment by caiusCitiriga** [comment]
Hi, sorry to reopen this, but it seems that the bug is still present on my Angular10 project. I've checked and the `@mapbox/mapbox-gl-draw` version is set to `^1.2.0` so it's to the latest one, but when I disable the `dragPan` on my map, the first interaction is prevented, but then if you immediately try to drag the map again the map can drag. 

Also an error is reported in the console:
```
Unable to preventDefault inside passive event listener invocation.
```

![Screenshot 2020-08-07 at 11 58 54](https://user-images.githubusercontent.com/12595721/89634310-74dc0080-d8a5-11ea-9a0b-b4483c5559d0.png

Can somebody please help me? I'm stuck on this and I need to keep the map still while the user draws the polygon 😢

**Pull request closed without merging**
