### PR TITLE
draw buttons should cancel on toggle

### PR DESCRIPTION
**Pull request by huaruiwu**
Relates to this issue https://github.com/mapbox/mapbox-gl-draw/issues/698. The buttons should actually toggle the mode you're in since it toggles `active` css class. If this makes sense I can modify the tests

### CODE REVIEW

**Comment by huaruiwu** [comment]
Any reason why my PR isn't being looked at or accepted?

**Comment by ansis** [comment]
Thanks for fixing this! Our maintenance of this library has not been where it should be. Thanks for the patience

**Comment by huaruiwu** [comment]
No problems, thank you for maintaining the library!

**Comment by krvajal** [comment]
Is this fix released?

**Comment by crow7m** [comment]
Was this released ? pretty important now
Thank you for maintaining

**Comment by kkaefer** [comment]
You can check out a beta release that includes this fix at https://github.com/mapbox/mapbox-gl-draw/releases/tag/v1.2.0-beta.1. It's also available via NPM.

**Pull request merged**
