### PR TITLE
allow features to have numeric ids

### LINKED ISSUE #738: draw.changeMode('direct_select', feature_id) not rerendering properly
**mapbox-gl-js version**: 0.43.0
**mapbox-gl-draw version**: 1.0.4

### Steps to Trigger Behavior
`feature` is an immutable Map.

```
const draw = new MapboxDraw({
  displayControlsDefault: false,
  controls: {
    polygon: true,
  },
});
map.addControl(draw);`
draw.add(feature.toJS());
draw.changeMode('direct_select', {featureId: feature.get('id')});
```

Drag one of the feature's vertices.

### Expected Behavior

Allows editing of the polygon and when vertices are dragged it renders the updated geometry on each frame.

### Actual Behavior

Old frames are not cleaned up and the geometry is "smeared" across the movement path.

example

### LINKED ISSUE #777: Editing a polygon that has been added to map with draw.add has some odd lagging behaviour.
I've encountered some strange behaviour with editing a polygon. It seems to be tied to having the draw mode "initialized" with "draw.add". When you try to edit the polygon and drag a vertex, it is never "cleared" from the frame and is layered on the last frame so you see bunch of vertices layered while dragging around.

[Dragging a vertex](http://res.cloudinary.com/exaptive/image/upload/c_fill,h_300,w_300/yti0fkdfjj3lzm0nilnw.png)

**mapbox-gl-js version**: 0.44.2
**mapbox-gl-draw version**: 1.0.4

### Steps to Trigger Behavior
 1. Navigate to https://codepen.io/jackwkinsey/pen/odoJJV?editors=0010
 2. Enter your Mapbox API Access Token at the top to make the code run.
 3. You should see polygons for Brazil.
 4. Double click on one of the polygons to allow it to be edited.
 5. Drag one of the vertices.

 OR

  Steps 1-3: Same as above.
  4. Click on the "Create Polygon" button in the top-right corner.
  5. Draw a new polygon, this is added to the Brazil set of polygons.
  6. Double click on your new polygon to allow it to edited.
  7. Drag one of the vertices.

### Expected Behavior
The polygon should be able to be edited freely and smoothly.

### Actual Behavior
The vertices and the polygon are never "redrawn" and "cleared" so you see a jagged bunch of vertices bunch up until you release and click off of the polygon.

### PR DESCRIPTION
**Pull request by mcwhittemore**
Closes #738
Closes #777

@mmoutenot do you take a look at this and confirm I've fixed the bug?

### CODE REVIEW

**Comment by mmoutenot** [comment]
Sorry for the delay. I reviewed the MR and it looks good 👍 

I have not had an opportunity yet to install this branch on my codebase, however.

**Comment by jackwkinsey** [comment]
I've confirmed that this fix should also address my issue as well!

Thanks!

**Comment by mcwhittemore** [comment]
@jackwkinsey & @mmoutenot - I've shipped 1.0.9 to npm.

@mollymerp - do version of gl-draw appear in the Mapbox CDN automagicly, or is there a next step I need to take to do that?

**Comment by friendlyswiss** [comment]
@mcwhittemore thanks for this fix!

It looks like a few methods still only take feature IDs as strings:

-get
-changeMode
-setFeatureProperty

Specifically, I'm running into problems using `draw.changeMode('direct_select', 'some_numeric_id')`.

I'm a non-dev working through a side project, so I'm grateful for any help. Thanks!

**Pull request merged**
