### PR TITLE
Exports fix + position option implementation

### PR DESCRIPTION
**Pull request by nsamala**
I kept getting a blank object when I tried using `require('mapbox-gl-draw')` with Browserify. I changed the way the module exports itself and it works now.

I also added code to support multiple ui positions similar to `mapboxgl.Navigation`

### CODE REVIEW

**Comment by mcwhittemore** [comment]
@nsamala thanks for this. Can you get the tests passing for the options ui?

**Comment by nsamala** [comment]
Sure thing! Looks like it was mainly some trailing spaces. Ran it locally so here's hoping :)

**Comment by mcwhittemore** [comment]
@nsamala - one small bug. If I try put the navigation control in a different corner than the draw control the draw control doesn't show up.

You can test this by tinkering with the debug/index.html file.

**Comment by nsamala** [comment]
Ah yeah I noticed that issue with the original control. I just pushed up a fix for that. It now works even in the absence of a navigation control

**Pull request merged**
