### PR TITLE
provide custom modes

### PR DESCRIPTION
**Pull request by primozs**
Could something like this be a start? #289 
I guess this would be more useful to somebody that would build this library himself.

### CODE REVIEW

**Comment by mcwhittemore** [comment]
@primozs - Thanks for this! I don't think this will negitivly effect one using this via a CDN.

I want to spin static mode out of gl-draw with this push. If you want to continue proving this change out, I'd recomend dropping static mode from the mode constants and finding a way to expose it to the debug mode.

**Comment by primozs** [comment]
Yes, it would not negatively effect CDN version but someone with custom modes needs might want to reuse more code from the lib.

I don't know about static mode but I need to implement some custom modes to see where I am and what problems I might stumble upon.

**Comment by primozs** [comment]
@mcwhittemore I have updated this commit with possibility to disable default modes. I also wired up defaultMode option that was already available. 
In general this works good for me.

**Comment by mcwhittemore** [comment]
Thanks! Can you provide an example so I know if I'm testing this the way you expect it to be used?

Regards,
Matthew

**Comment by primozs** [comment]
I am using it like this:
- "disableDefaultModes": false by default, all default draw modes are instantiated. When "disableDefaultModes" is true and no "defaultMode" it will trow an error with explanation. 
- "metaTypes" Specify and merge custom geojson meta types with default meta types constants. Like this "mousemove" can find custom geojson elements same as Vertex element.
-  "modes" object of key value. key is custom mode constant name and value is custom mode instance. when disableDefaultModes is false (default) custom modes are merged with default ones otherwise only custom modes are passed trough ctx
- modesConstants: same type of object as draw constants.js passed trough ctx for convenience 

```
this.draw = new MapboxDraw({
      disableDefaultModes: true, 
      defaultMode: cuDrawConstants.modes.CU_SIMPLE_SELECT,
      metaTypes: [
        cuDrawConstants.meta.OZONE,
        cuDrawConstants.meta.TASK_LINE
      ],
      modes: {
        [cuDrawConstants.modes.CU_STATIC]: cuStatic,
        [cuDrawConstants.modes.CU_SIMPLE_SELECT]: cuSimpleSelect,
        [cuDrawConstants.modes.CU_DIRECT_SELECT]: cuDirectSelect,
        [cuDrawConstants.modes.DRAW_CU_RULER]: cuDrawRuler,
        [cuDrawConstants.modes.DRAW_CU_POINT]: cuDrawPoint,
        [cuDrawConstants.modes.DRAW_CU_TASK]: cuDrawTask
      },
      modesConstants: cuDrawConstants.modes
    });

```

**Comment by mcwhittemore** [comment]
@primozs - thanks for your first pass at this. This has been finished via #671.

**Pull request closed without merging**
