### PR TITLE
#610 mobile ux improvements

### PR DESCRIPTION
**Pull request by z0d14c**
This PR adds an initial vertex when drawing a new line or polygon. Although more efforts could be made, this significantly improves UX by informing giving the user feedback on their input vs. none until they make 2 or 3 taps.

### CODE REVIEW

**Comment by mcwhittemore** [comment]
@z0d14c +1 to adding the handles from the start.

Before this PR, we only showed handles when the polygon was valid. But since we are now showing them from the start, lets make sure they are always showing. 

- First tap looks great!
- Second tap: both ends of the line should have handles but only the first does
- third Tap: first and last point should have points, but none do.
- Forth Tap: 1st and 4th positions should have points but 1st and 3rd due.
- 5+: like the forth tap, the last handle is one position back from where it should be.

**Comment by z0d14c** [comment]
@mcwhittemore I believe we're in a good spot now. The tests had to be modified a bit to account for the extra node that exists more often now. I think it's all functioning 💯 %

**Comment by mcwhittemore** [comment]
On mobile, when drawing a polygon, when I place the second point I just see two handles rather than handles points and a line.

Otherwise, this is looking good.

**Comment by andrewharvey** [comment]
Looking good to me, I can confirm seeing what @mcwhittemore mentioned already.

**Comment by z0d14c** [comment]
@mcwhittemore @andrewharvey ive fixed the behavior up to your specs, but now the polygon integration test is failing. honestly i cant figure out what the problem is and i think it may be a "false" failure, with jsts.min.js:9 throwing a cryptic error. specifically this occurs on the drawGeometry call in the `Polygon integration` test. Would love any input or assistance with this; drawing seems to work fine in an actual browser environment on mobile or desktop chrome.

**Comment by mcwhittemore** [comment]
@z0d14c - I'm looking at the tests now

**Comment by mcwhittemore** [comment]
@z0d14c - I added some console logging to `test/utils/draw_geometry` to capture when in the drawing processes this error was thrown.

```
pre-click [ 0, 0 ] false
post-click
pre-click [ 30, 15 ] false
```

The error happens after the second click. Looking at your PR, you changed the number of coordinates used for different rendering types in a few places. My guess is that this is resulting in a polygon with two points being rendered in the tests. This is an invalid polygon and would cause this kind of error.

I hope this helps as a place to start. Sorry if working with the tests is kind of hard. :(. I can also take a look tomorrow.

**Comment by z0d14c** [comment]
great feedback, i had figured out that it was failing on the 2nd point but i couldnt figure out why. thanks and ill try to get to this asap.

**Comment by z0d14c** [comment]
@mcwhittemore @andrewharvey I think we're in a good place now.

**Comment by mcwhittemore** [comment]
@andrewharvey - does this PR solve this problem? https://github.com/mapbox/mapbox-gl-draw/issues/650

**Comment by andrewharvey** [comment]
@mcwhittemore It seems to be unrelated, ie. I notice #650 in both master and the latest version of this PR. So let's not let #650 hold this PR up.

**Comment by z0d14c** [comment]
can we go ahead and merge?

**Comment by z0d14c** [comment]
(I can't click the merge button)

**Comment by mcwhittemore** [comment]
merged in 7a7313107d7d50b1ce664274823a7e6cb60c691e

**Pull request closed without merging**
