### PR TITLE
Fix some warnings

### PR DESCRIPTION
**Pull request by mike-marcacci**
I don't believe these have any impact on the code that gets installed/run, but appeases warnings that clutter my build logs.

### CODE REVIEW

**Comment by mcwhittemore** [comment]
Thanks for this. Can you update the references to the modules in the code base so the tests pass and then we'll be good to go.

**Comment by mike-marcacci** [comment]
Ah yes – sorry about that. I also realized `yarn.lock` was going to need to reflect the changes. Simply running `yarn install` made a few more diffs, though, so it may have already been out of date (not sure if you guys mostly use yarn or npm at Mapbox).

**Comment by mcwhittemore** [comment]
this is now part of [v1.0.3](https://github.com/mapbox/mapbox-gl-draw/releases/tag/v1.0.3) and has been published to npm.

**Comment by mike-marcacci** [comment]
Awesome, thanks!

**Pull request merged**
