### PR TITLE
Update mapbox-gl peerDependency

### PR DESCRIPTION
**Pull request by drewbo**
Maybe a little overkill at this point but don't want to leave behind `0.13` yet

### CODE REVIEW

**Comment by lucaswoj** [comment]
My understanding is that `^0.13.0` includes `0.13.x` as well as `0.14.x`, `0.15.x`, etc.

`~0.13.0` would only include `0.13.x`

We should remove the `|| ^0.15.0`

cc @kelvinabrokwa @mcwhittemore

**Comment by drewbo** [comment]
I think pre `1.0.0` npm assumes that minor versions can be breaking. Maybe it could update to `<=` syntax?

https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

**Comment by lucaswoj** [comment]
Ah! You're right @drewbo.

**Comment by mcwhittemore** [comment]
This looks good. I'll push out a release.

**Pull request merged**
